# Generated by Django 2.2.3 on 2019-07-11 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_RGMU', models.CharField(max_length=1000)),
                ('region', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
