# Generated by Django 2.2.3 on 2019-08-14 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='region_name',
            field=models.TextField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='time',
            field=models.TimeField(default=datetime.time(15, 54, 33, 253861)),
        ),
    ]
