# Generated by Django 2.2.3 on 2019-08-15 04:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190814_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionmodel',
            name='time',
            field=models.TimeField(default=datetime.time(9, 30, 47, 952842)),
        ),
    ]
