# Generated by Django 2.2.3 on 2019-07-11 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190711_0907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regionmodel',
            options={'ordering': ('-date_time',)},
        ),
        migrations.RenameField(
            model_name='regionmodel',
            old_name='region',
            new_name='region_name',
        ),
    ]
