# Generated by Django 2.2.3 on 2019-08-20 04:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190819_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionmodel',
            name='day',
            field=models.CharField(default='20', max_length=2),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='time',
            field=models.TimeField(default=datetime.time(9, 49, 4, 478094)),
        ),
    ]
