# Generated by Django 2.2.3 on 2019-08-20 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190820_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regionmodel',
            options={'ordering': ['-year', '-month', '-day', '-time']},
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='time',
            field=models.TimeField(default=datetime.time(13, 10, 31, 440101)),
        ),
    ]
