# Generated by Django 2.2.3 on 2019-07-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190711_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regionmodel',
            old_name='id_RGMU',
            new_name='acceptance_of_applications_and_issuance_of_documents_id_RGMU',
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='acceptance_of_applications_and_issuance_of_documents_link',
            field=models.CharField(default='my_link', max_length=1000),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='acceptance_of_applications_and_issuance_of_documents_statement_amount',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
