# Generated by Django 2.2.3 on 2019-07-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190711_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionmodel',
            name='acceptance_of_applications_and_issuance_of_documents_has_advanced_appointmnet',
            field=models.CharField(choices=[('YES', 'Да'), ('NOT_PROVIDED', 'Не предусмотрено'), ('NO', 'Нет')], default='NO', max_length=12),
        ),
    ]
