# Generated by Django 2.2.3 on 2019-07-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_regionmodel_acceptance_of_applications_and_issuance_of_documents_has_advanced_appointmnet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regionmodel',
            old_name='acceptance_of_applications_and_issuance_of_documents_has_advanced_appointmnet',
            new_name='acceptance_of_applications_and_issuance_of_documents_has_advanced_appointment',
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='acceptance_of_applications_and_issuance_of_documents_has_advanced_appointment_comment',
            field=models.TextField(default=''),
        ),
    ]
