# Generated by Django 2.2.3 on 2019-08-20 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190820_1315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regionmodel',
            options={},
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='time',
            field=models.TimeField(default=datetime.time(13, 16, 14, 627047)),
        ),
    ]
