# Generated by Django 2.2.3 on 2019-08-15 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190815_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionmodel',
            name='day',
            field=models.CharField(default='15', max_length=2),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='month',
            field=models.CharField(default='08', max_length=2),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='time',
            field=models.TimeField(default=datetime.time(11, 59, 3, 467491)),
        ),
    ]
