# Generated by Django 2.2.3 on 2019-08-19 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190815_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionmodel',
            name='day',
            field=models.CharField(default='19', max_length=2),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='time',
            field=models.TimeField(default=datetime.time(10, 40, 13, 646788)),
        ),
    ]
