# Generated by Django 2.2.3 on 2019-07-12 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190712_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionmodel',
            name='acceptance_of_applications_and_issuance_of_documents_connected_to_FGIS_DO',
        ),
        migrations.RemoveField(
            model_name='regionmodel',
            name='acceptance_of_applications_and_issuance_of_documents_connected_to_FGIS_DO_comment',
        ),
        migrations.RemoveField(
            model_name='regionmodel',
            name='acceptance_of_applications_and_issuance_of_documents_has_causes_of_failure',
        ),
        migrations.RemoveField(
            model_name='regionmodel',
            name='acceptance_of_applications_and_issuance_of_documents_has_causes_of_failure_comment',
        ),
        migrations.RemoveField(
            model_name='regionmodel',
            name='acceptance_of_applications_and_issuance_of_documents_has_documnet_template',
        ),
        migrations.RemoveField(
            model_name='regionmodel',
            name='acceptance_of_applications_and_issuance_of_documents_has_documnet_template_comment',
        ),
        migrations.RemoveField(
            model_name='regionmodel',
            name='acceptance_of_applications_and_issuance_of_documents_has_edition_draft',
        ),
        migrations.RemoveField(
            model_name='regionmodel',
            name='acceptance_of_applications_and_issuance_of_documents_has_edition_draft_comment',
        ),
        migrations.RemoveField(
            model_name='regionmodel',
            name='acceptance_of_applications_and_issuance_of_documents_has_electronic_form_printing',
        ),
        migrations.RemoveField(
            model_name='regionmodel',
            name='acceptance_of_applications_and_issuance_of_documents_has_electronic_form_printing_comment',
        ),
        migrations.RemoveField(
            model_name='regionmodel',
            name='acceptance_of_applications_and_issuance_of_documents_has_estimation_quality',
        ),
        migrations.RemoveField(
            model_name='regionmodel',
            name='acceptance_of_applications_and_issuance_of_documents_has_estimation_quality_comment',
        ),
        migrations.RemoveField(
            model_name='regionmodel',
            name='acceptance_of_applications_and_issuance_of_documents_has_notification_of_consideration_result',
        ),
        migrations.RemoveField(
            model_name='regionmodel',
            name='acceptance_of_applications_and_issuance_of_documents_has_notification_of_consideration_result_comment',
        ),
        migrations.RemoveField(
            model_name='regionmodel',
            name='acceptance_of_applications_and_issuance_of_documents_has_reglament',
        ),
        migrations.RemoveField(
            model_name='regionmodel',
            name='acceptance_of_applications_and_issuance_of_documents_has_reglament_comment',
        ),
        migrations.RemoveField(
            model_name='regionmodel',
            name='acceptance_of_applications_and_issuance_of_documents_has_sample_document',
        ),
        migrations.RemoveField(
            model_name='regionmodel',
            name='acceptance_of_applications_and_issuance_of_documents_has_sample_document_comment',
        ),
        migrations.RemoveField(
            model_name='regionmodel',
            name='acceptance_of_applications_and_issuance_of_documents_has_term_of_consideration',
        ),
        migrations.RemoveField(
            model_name='regionmodel',
            name='acceptance_of_applications_and_issuance_of_documents_has_term_of_consideration_comment',
        ),
    ]
