# Generated by Django 2.2.3 on 2019-09-05 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190820_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionmodel',
            name='free_land_provision_connected_to_fgis_do',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='free_land_provision_connected_to_fgis_do_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='free_land_provision_has_advanced_appointment',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='free_land_provision_has_advanced_appointment_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='free_land_provision_has_btn_get_service',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='free_land_provision_has_btn_get_service_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='free_land_provision_has_causes_of_failure',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='free_land_provision_has_causes_of_failure_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='free_land_provision_has_document_template',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='free_land_provision_has_document_template_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='free_land_provision_has_edition_draft',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='free_land_provision_has_edition_draft_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='free_land_provision_has_electronic_form_printing',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='free_land_provision_has_electronic_form_printing_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='free_land_provision_has_estimation_quality',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='free_land_provision_has_estimation_quality_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='free_land_provision_has_notif_consider_result',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='free_land_provision_has_notif_consider_result_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='free_land_provision_has_reglament',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='free_land_provision_has_reglament_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='free_land_provision_has_sample_document',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='free_land_provision_has_sample_document_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='free_land_provision_has_term_of_consideration',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='free_land_provision_has_term_of_consideration_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='free_land_provision_id_rgmu',
            field=models.CharField(default='111', max_length=1000),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='free_land_provision_link',
            field=models.CharField(default='my_link', max_length=1000),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='free_land_provision_statement_amount',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_lease_connected_to_fgis_do',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_lease_connected_to_fgis_do_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_lease_has_advanced_appointment',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_lease_has_advanced_appointment_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_lease_has_btn_get_service',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_lease_has_btn_get_service_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_lease_has_causes_of_failure',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_lease_has_causes_of_failure_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_lease_has_document_template',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_lease_has_document_template_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_lease_has_edition_draft',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_lease_has_edition_draft_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_lease_has_electronic_form_printing',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_lease_has_electronic_form_printing_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_lease_has_estimation_quality',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_lease_has_estimation_quality_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_lease_has_notif_consider_result',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_lease_has_notif_consider_result_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_lease_has_reglament',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_lease_has_reglament_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_lease_has_sample_document',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_lease_has_sample_document_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_lease_has_term_of_consideration',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_lease_has_term_of_consideration_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_lease_id_rgmu',
            field=models.CharField(default='111', max_length=1000),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_lease_link',
            field=models.CharField(default='my_link', max_length=1000),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_lease_statement_amount',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_sale_connected_to_fgis_do',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_sale_connected_to_fgis_do_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_sale_has_advanced_appointment',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_sale_has_advanced_appointment_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_sale_has_btn_get_service',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_sale_has_btn_get_service_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_sale_has_causes_of_failure',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_sale_has_causes_of_failure_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_sale_has_document_template',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_sale_has_document_template_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_sale_has_edition_draft',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_sale_has_edition_draft_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_sale_has_electronic_form_printing',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_sale_has_electronic_form_printing_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_sale_has_estimation_quality',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_sale_has_estimation_quality_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_sale_has_notif_consider_result',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_sale_has_notif_consider_result_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_sale_has_reglament',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_sale_has_reglament_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_sale_has_sample_document',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_sale_has_sample_document_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_sale_has_term_of_consideration',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_sale_has_term_of_consideration_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_sale_id_rgmu',
            field=models.CharField(default='111', max_length=1000),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_sale_link',
            field=models.CharField(default='my_link', max_length=1000),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_sale_statement_amount',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='municipal_property_lease_connected_to_fgis_do',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='municipal_property_lease_connected_to_fgis_do_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='municipal_property_lease_has_advanced_appointment',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='municipal_property_lease_has_advanced_appointment_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='municipal_property_lease_has_btn_get_service',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='municipal_property_lease_has_btn_get_service_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='municipal_property_lease_has_causes_of_failure',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='municipal_property_lease_has_causes_of_failure_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='municipal_property_lease_has_document_template',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='municipal_property_lease_has_document_template_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='municipal_property_lease_has_edition_draft',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='municipal_property_lease_has_edition_draft_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='municipal_property_lease_has_electronic_form_printing',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='municipal_property_lease_has_electronic_form_printing_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='municipal_property_lease_has_estimation_quality',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='municipal_property_lease_has_estimation_quality_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='municipal_property_lease_has_notif_consider_result',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='municipal_property_lease_has_notif_consider_result_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='municipal_property_lease_has_reglament',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='municipal_property_lease_has_reglament_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='municipal_property_lease_has_sample_document',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='municipal_property_lease_has_sample_document_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='municipal_property_lease_has_term_of_consideration',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='municipal_property_lease_has_term_of_consideration_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='municipal_property_lease_id_rgmu',
            field=models.CharField(default='111', max_length=1000),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='municipal_property_lease_link',
            field=models.CharField(default='my_link', max_length=1000),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='municipal_property_lease_statement_amount',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='ownership_right_connected_to_fgis_do',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='ownership_right_connected_to_fgis_do_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='ownership_right_has_advanced_appointment',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='ownership_right_has_advanced_appointment_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='ownership_right_has_btn_get_service',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='ownership_right_has_btn_get_service_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='ownership_right_has_causes_of_failure',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='ownership_right_has_causes_of_failure_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='ownership_right_has_document_template',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='ownership_right_has_document_template_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='ownership_right_has_edition_draft',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='ownership_right_has_edition_draft_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='ownership_right_has_electronic_form_printing',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='ownership_right_has_electronic_form_printing_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='ownership_right_has_estimation_quality',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='ownership_right_has_estimation_quality_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='ownership_right_has_notif_consider_result',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='ownership_right_has_notif_consider_result_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='ownership_right_has_reglament',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='ownership_right_has_reglament_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='ownership_right_has_sample_document',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='ownership_right_has_sample_document_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='ownership_right_has_term_of_consideration',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='ownership_right_has_term_of_consideration_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='ownership_right_id_rgmu',
            field=models.CharField(default='111', max_length=1000),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='ownership_right_link',
            field=models.CharField(default='my_link', max_length=1000),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='ownership_right_statement_amount',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='day',
            field=models.CharField(default='05', max_length=2),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='month',
            field=models.CharField(default='09', max_length=2),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='time',
            field=models.TimeField(default=datetime.time(12, 19, 1, 505206)),
        ),
    ]
