# Generated by Django 2.2.3 on 2019-08-19 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190819_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionmodel',
            name='time',
            field=models.TimeField(default=datetime.time(13, 4, 37, 596177)),
        ),
    ]
