# Generated by Django 2.2.3 on 2019-10-07 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20191008_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionmodel',
            name='time',
            field=models.TimeField(default=datetime.time(0, 48, 7, 970849)),
        ),
    ]
