# Generated by Django 2.2.3 on 2019-07-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190717_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
