# Generated by Django 2.2.3 on 2019-07-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190717_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionmodel',
            name='housing_transfer_connected_to_FGIS_DO',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='housing_transfer_connected_to_FGIS_DO_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='housing_transfer_has_advanced_appointment',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='housing_transfer_has_advanced_appointment_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='housing_transfer_has_btn_get_service',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='housing_transfer_has_btn_get_service_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='housing_transfer_has_causes_of_failure',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='housing_transfer_has_causes_of_failure_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='housing_transfer_has_document_template_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='housing_transfer_has_documnet_template',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='housing_transfer_has_edition_draft',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='housing_transfer_has_edition_draft_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='housing_transfer_has_electronic_form_printing',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='housing_transfer_has_electronic_form_printing_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='housing_transfer_has_estimation_quality',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='housing_transfer_has_estimation_quality_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='housing_transfer_has_notification_of_consideration_result',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='housing_transfer_has_notification_of_consideration_result_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='housing_transfer_has_reglament',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='housing_transfer_has_reglament_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='housing_transfer_has_sample_document',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='housing_transfer_has_sample_document_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='housing_transfer_has_term_of_consideration',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='housing_transfer_has_term_of_consideration_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='housing_transfer_id_RGMU',
            field=models.CharField(default='111', max_length=1000),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='housing_transfer_link',
            field=models.CharField(default='my_link', max_length=1000),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='housing_transfer_statement_amount',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='redevelopment_residential_premises_id_RGMU',
            field=models.CharField(default='111', max_length=1000),
        ),
    ]
