# Generated by Django 2.2.3 on 2019-07-18 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190718_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regionmodel',
            old_name='housing_transfer_has_documnet_template',
            new_name='housing_transfer_has_document_template',
        ),
    ]
