# Generated by Django 2.2.3 on 2019-07-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190718_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionmodel',
            name='housing_transfer_connected_to_FGIS_DO',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='housing_transfer_has_causes_of_failure',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='housing_transfer_has_document_template',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='housing_transfer_has_edition_draft',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='housing_transfer_has_electronic_form_printing',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='housing_transfer_has_estimation_quality',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='housing_transfer_has_notification_of_consideration_result',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='housing_transfer_has_sample_document',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='housing_transfer_has_term_of_consideration',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='redevelopment_residential_premises_connected_to_FGIS_DO',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='redevelopment_residential_premises_has_causes_of_failure',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='redevelopment_residential_premises_has_documnet_template',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='redevelopment_residential_premises_has_edition_draft',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='redevelopment_residential_premises_has_electronic_form_printing',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='redevelopment_residential_premises_has_estimation_quality',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='redevelopment_residential_premises_has_notification_of_consideration_result',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='redevelopment_residential_premises_has_sample_document',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='redevelopment_residential_premises_has_term_of_consideration',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
    ]
