# Generated by Django 2.2.3 on 2019-07-18 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190718_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regionmodel',
            old_name='redevelopment_residential_premises_has_documnet_template',
            new_name='redevelopment_residential_premises_has_document_template',
        ),
    ]
