# Generated by Django 2.2.3 on 2019-07-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20190718_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionmodel',
            name='advertising_structures_connected_to_FGIS_DO',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='advertising_structures_connected_to_FGIS_DO_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='advertising_structures_has_advanced_appointment',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='advertising_structures_has_advanced_appointment_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='advertising_structures_has_btn_get_service',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='advertising_structures_has_btn_get_service_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='advertising_structures_has_causes_of_failure',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='advertising_structures_has_causes_of_failure_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='advertising_structures_has_document_template',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='advertising_structures_has_document_template_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='advertising_structures_has_edition_draft',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='advertising_structures_has_edition_draft_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='advertising_structures_has_electronic_form_printing',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='advertising_structures_has_electronic_form_printing_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='advertising_structures_has_estimation_quality',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='advertising_structures_has_estimation_quality_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='advertising_structures_has_notification_of_consideration_result',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='advertising_structures_has_notification_of_consideration_result_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='advertising_structures_has_reglament',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='advertising_structures_has_reglament_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='advertising_structures_has_sample_document',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='advertising_structures_has_sample_document_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='advertising_structures_has_term_of_consideration',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='advertising_structures_has_term_of_consideration_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='advertising_structures_id_RGMU',
            field=models.CharField(default='111', max_length=1000),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='advertising_structures_link',
            field=models.CharField(default='my_link', max_length=1000),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='advertising_structures_statement_amount',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='archive_reference_connected_to_FGIS_DO',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='archive_reference_connected_to_FGIS_DO_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='archive_reference_has_advanced_appointment',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='archive_reference_has_advanced_appointment_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='archive_reference_has_btn_get_service',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='archive_reference_has_btn_get_service_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='archive_reference_has_causes_of_failure',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='archive_reference_has_causes_of_failure_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='archive_reference_has_document_template',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='archive_reference_has_document_template_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='archive_reference_has_edition_draft',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='archive_reference_has_edition_draft_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='archive_reference_has_electronic_form_printing',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='archive_reference_has_electronic_form_printing_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='archive_reference_has_estimation_quality',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='archive_reference_has_estimation_quality_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='archive_reference_has_notification_of_consideration_result',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='archive_reference_has_notification_of_consideration_result_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='archive_reference_has_reglament',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='archive_reference_has_reglament_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='archive_reference_has_sample_document',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='archive_reference_has_sample_document_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='archive_reference_has_term_of_consideration',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='archive_reference_has_term_of_consideration_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='archive_reference_id_RGMU',
            field=models.CharField(default='111', max_length=1000),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='archive_reference_link',
            field=models.CharField(default='my_link', max_length=1000),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='archive_reference_statement_amount',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='capital_construction_connected_to_FGIS_DO',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='capital_construction_connected_to_FGIS_DO_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='capital_construction_has_advanced_appointment',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='capital_construction_has_advanced_appointment_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='capital_construction_has_btn_get_service',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='capital_construction_has_btn_get_service_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='capital_construction_has_causes_of_failure',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='capital_construction_has_causes_of_failure_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='capital_construction_has_document_template',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='capital_construction_has_document_template_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='capital_construction_has_edition_draft',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='capital_construction_has_edition_draft_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='capital_construction_has_electronic_form_printing',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='capital_construction_has_electronic_form_printing_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='capital_construction_has_estimation_quality',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='capital_construction_has_estimation_quality_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='capital_construction_has_notification_of_consideration_result',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='capital_construction_has_notification_of_consideration_result_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='capital_construction_has_reglament',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='capital_construction_has_reglament_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='capital_construction_has_sample_document',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='capital_construction_has_sample_document_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='capital_construction_has_term_of_consideration',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='capital_construction_has_term_of_consideration_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='capital_construction_id_RGMU',
            field=models.CharField(default='111', max_length=1000),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='capital_construction_link',
            field=models.CharField(default='my_link', max_length=1000),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='capital_construction_statement_amount',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_preschool_education_connected_to_FGIS_DO',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_preschool_education_connected_to_FGIS_DO_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_preschool_education_has_advanced_appointment',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_preschool_education_has_advanced_appointment_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_preschool_education_has_btn_get_service',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_preschool_education_has_btn_get_service_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_preschool_education_has_causes_of_failure',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_preschool_education_has_causes_of_failure_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_preschool_education_has_document_template',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_preschool_education_has_document_template_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_preschool_education_has_edition_draft',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_preschool_education_has_edition_draft_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_preschool_education_has_electronic_form_printing',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_preschool_education_has_electronic_form_printing_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_preschool_education_has_estimation_quality',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_preschool_education_has_estimation_quality_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_preschool_education_has_notification_of_consideration_result',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_preschool_education_has_notification_of_consideration_result_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_preschool_education_has_reglament',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_preschool_education_has_reglament_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_preschool_education_has_sample_document',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_preschool_education_has_sample_document_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_preschool_education_has_term_of_consideration',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_preschool_education_has_term_of_consideration_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_preschool_education_id_RGMU',
            field=models.CharField(default='111', max_length=1000),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_preschool_education_link',
            field=models.CharField(default='my_link', max_length=1000),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_preschool_education_statement_amount',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_school_education_connected_to_FGIS_DO',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_school_education_connected_to_FGIS_DO_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_school_education_has_advanced_appointment',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_school_education_has_advanced_appointment_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_school_education_has_btn_get_service',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_school_education_has_btn_get_service_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_school_education_has_causes_of_failure',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_school_education_has_causes_of_failure_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_school_education_has_document_template',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_school_education_has_document_template_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_school_education_has_edition_draft',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_school_education_has_edition_draft_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_school_education_has_electronic_form_printing',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_school_education_has_electronic_form_printing_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_school_education_has_estimation_quality',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_school_education_has_estimation_quality_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_school_education_has_notification_of_consideration_result',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_school_education_has_notification_of_consideration_result_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_school_education_has_reglament',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_school_education_has_reglament_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_school_education_has_sample_document',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_school_education_has_sample_document_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_school_education_has_term_of_consideration',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_school_education_has_term_of_consideration_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_school_education_id_RGMU',
            field=models.CharField(default='111', max_length=1000),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_school_education_link',
            field=models.CharField(default='my_link', max_length=1000),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='institutions_school_education_statement_amount',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_location_schemes_connected_to_FGIS_DO',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_location_schemes_connected_to_FGIS_DO_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_location_schemes_has_advanced_appointment',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_location_schemes_has_advanced_appointment_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_location_schemes_has_btn_get_service',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_location_schemes_has_btn_get_service_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_location_schemes_has_causes_of_failure',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_location_schemes_has_causes_of_failure_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_location_schemes_has_document_template',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_location_schemes_has_document_template_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_location_schemes_has_edition_draft',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_location_schemes_has_edition_draft_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_location_schemes_has_electronic_form_printing',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_location_schemes_has_electronic_form_printing_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_location_schemes_has_estimation_quality',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_location_schemes_has_estimation_quality_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_location_schemes_has_notification_of_consideration_result',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_location_schemes_has_notification_of_consideration_result_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_location_schemes_has_reglament',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_location_schemes_has_reglament_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_location_schemes_has_sample_document',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_location_schemes_has_sample_document_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_location_schemes_has_term_of_consideration',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_location_schemes_has_term_of_consideration_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_location_schemes_id_RGMU',
            field=models.CharField(default='111', max_length=1000),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_location_schemes_link',
            field=models.CharField(default='my_link', max_length=1000),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='land_location_schemes_statement_amount',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='needing_residential_premises_connected_to_FGIS_DO',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='needing_residential_premises_connected_to_FGIS_DO_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='needing_residential_premises_has_advanced_appointment',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='needing_residential_premises_has_advanced_appointment_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='needing_residential_premises_has_btn_get_service',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='needing_residential_premises_has_btn_get_service_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='needing_residential_premises_has_causes_of_failure',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='needing_residential_premises_has_causes_of_failure_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='needing_residential_premises_has_document_template',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='needing_residential_premises_has_document_template_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='needing_residential_premises_has_edition_draft',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='needing_residential_premises_has_edition_draft_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='needing_residential_premises_has_electronic_form_printing',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='needing_residential_premises_has_electronic_form_printing_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='needing_residential_premises_has_estimation_quality',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='needing_residential_premises_has_estimation_quality_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='needing_residential_premises_has_notification_of_consideration_result',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='needing_residential_premises_has_notification_of_consideration_result_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='needing_residential_premises_has_reglament',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='needing_residential_premises_has_reglament_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='needing_residential_premises_has_sample_document',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='needing_residential_premises_has_sample_document_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='needing_residential_premises_has_term_of_consideration',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='needing_residential_premises_has_term_of_consideration_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='needing_residential_premises_id_RGMU',
            field=models.CharField(default='111', max_length=1000),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='needing_residential_premises_link',
            field=models.CharField(default='my_link', max_length=1000),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='needing_residential_premises_statement_amount',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='town_planning_plans_connected_to_FGIS_DO',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='town_planning_plans_connected_to_FGIS_DO_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='town_planning_plans_has_advanced_appointment',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='town_planning_plans_has_advanced_appointment_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='town_planning_plans_has_btn_get_service',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='town_planning_plans_has_btn_get_service_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='town_planning_plans_has_causes_of_failure',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='town_planning_plans_has_causes_of_failure_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='town_planning_plans_has_document_template',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='town_planning_plans_has_document_template_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='town_planning_plans_has_edition_draft',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='town_planning_plans_has_edition_draft_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='town_planning_plans_has_electronic_form_printing',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='town_planning_plans_has_electronic_form_printing_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='town_planning_plans_has_estimation_quality',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='town_planning_plans_has_estimation_quality_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='town_planning_plans_has_notification_of_consideration_result',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='town_planning_plans_has_notification_of_consideration_result_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='town_planning_plans_has_reglament',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='town_planning_plans_has_reglament_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='town_planning_plans_has_sample_document',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='town_planning_plans_has_sample_document_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='town_planning_plans_has_term_of_consideration',
            field=models.CharField(choices=[('Да', 'Да'), ('Не предусмотрено', 'Не предусмотрено'), ('Нет', 'Нет')], default='Да', max_length=20),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='town_planning_plans_has_term_of_consideration_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='town_planning_plans_id_RGMU',
            field=models.CharField(default='111', max_length=1000),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='town_planning_plans_link',
            field=models.CharField(default='my_link', max_length=1000),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='town_planning_plans_statement_amount',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
