# Generated by Django 2.2.3 on 2019-07-23 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20190718_1235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regionmodel',
            options={},
        ),
    ]
