# Generated by Django 2.2.3 on 2019-07-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20190723_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionmodel',
            name='advertising_structures_connected_to_FGIS_DO_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='advertising_structures_has_advanced_appointment_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='advertising_structures_has_btn_get_service_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='advertising_structures_has_causes_of_failure_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='advertising_structures_has_document_template_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='advertising_structures_has_edition_draft_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='advertising_structures_has_electronic_form_printing_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='advertising_structures_has_estimation_quality_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='advertising_structures_has_notification_of_consideration_result_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='advertising_structures_has_reglament_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='advertising_structures_has_sample_document_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='advertising_structures_has_term_of_consideration_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='archive_reference_connected_to_FGIS_DO_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='archive_reference_has_advanced_appointment_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='archive_reference_has_btn_get_service_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='archive_reference_has_causes_of_failure_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='archive_reference_has_document_template_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='archive_reference_has_edition_draft_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='archive_reference_has_electronic_form_printing_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='archive_reference_has_estimation_quality_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='archive_reference_has_notification_of_consideration_result_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='archive_reference_has_reglament_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='archive_reference_has_sample_document_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='archive_reference_has_term_of_consideration_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='capital_construction_connected_to_FGIS_DO_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='capital_construction_has_advanced_appointment_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='capital_construction_has_btn_get_service_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='capital_construction_has_causes_of_failure_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='capital_construction_has_document_template_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='capital_construction_has_edition_draft_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='capital_construction_has_electronic_form_printing_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='capital_construction_has_estimation_quality_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='capital_construction_has_notification_of_consideration_result_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='capital_construction_has_reglament_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='capital_construction_has_sample_document_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='capital_construction_has_term_of_consideration_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='housing_transfer_connected_to_FGIS_DO_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='housing_transfer_has_advanced_appointment_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='housing_transfer_has_btn_get_service_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='housing_transfer_has_causes_of_failure_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='housing_transfer_has_document_template_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='housing_transfer_has_edition_draft_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='housing_transfer_has_electronic_form_printing_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='housing_transfer_has_estimation_quality_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='housing_transfer_has_notification_of_consideration_result_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='housing_transfer_has_reglament_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='housing_transfer_has_sample_document_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='housing_transfer_has_term_of_consideration_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='institutions_preschool_education_connected_to_FGIS_DO_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='institutions_preschool_education_has_advanced_appointment_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='institutions_preschool_education_has_btn_get_service_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='institutions_preschool_education_has_causes_of_failure_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='institutions_preschool_education_has_document_template_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='institutions_preschool_education_has_edition_draft_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='institutions_preschool_education_has_electronic_form_printing_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='institutions_preschool_education_has_estimation_quality_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='institutions_preschool_education_has_notification_of_consideration_result_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='institutions_preschool_education_has_reglament_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='institutions_preschool_education_has_sample_document_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='institutions_preschool_education_has_term_of_consideration_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='institutions_school_education_connected_to_FGIS_DO_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='institutions_school_education_has_advanced_appointment_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='institutions_school_education_has_btn_get_service_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='institutions_school_education_has_causes_of_failure_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='institutions_school_education_has_document_template_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='institutions_school_education_has_edition_draft_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='institutions_school_education_has_electronic_form_printing_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='institutions_school_education_has_estimation_quality_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='institutions_school_education_has_notification_of_consideration_result_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='institutions_school_education_has_reglament_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='institutions_school_education_has_sample_document_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='institutions_school_education_has_term_of_consideration_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='land_location_schemes_connected_to_FGIS_DO_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='land_location_schemes_has_advanced_appointment_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='land_location_schemes_has_btn_get_service_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='land_location_schemes_has_causes_of_failure_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='land_location_schemes_has_document_template_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='land_location_schemes_has_edition_draft_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='land_location_schemes_has_electronic_form_printing_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='land_location_schemes_has_estimation_quality_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='land_location_schemes_has_notification_of_consideration_result_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='land_location_schemes_has_reglament_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='land_location_schemes_has_sample_document_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='land_location_schemes_has_term_of_consideration_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='needing_residential_premises_connected_to_FGIS_DO_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='needing_residential_premises_has_advanced_appointment_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='needing_residential_premises_has_btn_get_service_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='needing_residential_premises_has_causes_of_failure_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='needing_residential_premises_has_document_template_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='needing_residential_premises_has_edition_draft_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='needing_residential_premises_has_electronic_form_printing_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='needing_residential_premises_has_estimation_quality_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='needing_residential_premises_has_notification_of_consideration_result_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='needing_residential_premises_has_reglament_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='needing_residential_premises_has_sample_document_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='needing_residential_premises_has_term_of_consideration_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='redevelopment_residential_premises_connected_to_FGIS_DO_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='redevelopment_residential_premises_has_advanced_appointment_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='redevelopment_residential_premises_has_btn_get_service_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='redevelopment_residential_premises_has_causes_of_failure_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='redevelopment_residential_premises_has_document_template_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='redevelopment_residential_premises_has_edition_draft_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='redevelopment_residential_premises_has_electronic_form_printing_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='redevelopment_residential_premises_has_estimation_quality_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='redevelopment_residential_premises_has_notification_of_consideration_result_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='redevelopment_residential_premises_has_reglament_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='redevelopment_residential_premises_has_sample_document_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='redevelopment_residential_premises_has_term_of_consideration_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='town_planning_plans_connected_to_FGIS_DO_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='town_planning_plans_has_advanced_appointment_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='town_planning_plans_has_btn_get_service_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='town_planning_plans_has_causes_of_failure_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='town_planning_plans_has_document_template_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='town_planning_plans_has_edition_draft_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='town_planning_plans_has_electronic_form_printing_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='town_planning_plans_has_estimation_quality_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='town_planning_plans_has_notification_of_consideration_result_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='town_planning_plans_has_reglament_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='town_planning_plans_has_sample_document_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='town_planning_plans_has_term_of_consideration_comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
