# Generated by Django 2.2.3 on 2019-07-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20190723_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionmodel',
            name='date_time',
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='month',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='year',
            field=models.IntegerField(default=2019),
        ),
    ]
