# Generated by Django 2.2.3 on 2019-07-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20190723_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionmodel',
            name='month',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='year',
            field=models.IntegerField(blank=True, default=2019),
        ),
    ]
