# Generated by Django 2.2.3 on 2019-07-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20190723_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionmodel',
            name='month',
            field=models.CharField(blank=True, default='01', max_length=2),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='year',
            field=models.CharField(blank=True, default='2019', max_length=4),
        ),
    ]
