# Generated by Django 2.2.3 on 2019-07-25 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20190724_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionmodel',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 25, 12, 43, 12, 748760)),
        ),
    ]
