# Generated by Django 2.2.3 on 2019-07-26 04:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_regionmodel_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionmodel',
            name='date_time',
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='day',
            field=models.CharField(default='01', max_length=2),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='time',
            field=models.TimeField(default=datetime.time(9, 27, 5, 913326)),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='month',
            field=models.CharField(default='01', max_length=2),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='year',
            field=models.CharField(default='2019', max_length=4),
        ),
    ]
