# Generated by Django 2.2.3 on 2019-07-26 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20190726_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionmodel',
            name='has_troubles',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Нет', max_length=3),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='time',
            field=models.TimeField(default=datetime.time(10, 55, 46, 540448)),
        ),
    ]
